### ISSUE TITLE
Rename to elm-events-extra for 0.19?

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-pointer-events#11]
Initially, this only handled pointer events. Then to reduce number of packages and name conflicts, it has been [merged with elm-mouse-events and elm-touch-events](https://discourse.elm-lang.org/t/package-for-mouse-touch-pointer-wheel-and-drag-apis/704). Then, because I was doing some file dropping stuff, I added the `Drag` module. Finally, since it seemed that the only "pointer-like" related thing missing was wheel, I added a `Wheel` module.

Due to module name conflicts for `Mouse` with elm-lang/mouse (see issue #9) and `Touch` with zwilias/elm-touch-events, I'm adding the `Events.Extra` prefix namespace to my modules (dc7dd8a).

So, as an after thought, I'm now wondering if renaming the package to elm-events-extra would make sense, even if this is focused on pointer-related stuff.

**Comment by mpizenberg** [comment]
Or even `Html.Events.Extra` prefix to have the imports next to `Html.Events` since they are related. So then rename the package **elm-html-events-extra**? Maybe that's too generic. Maybe there can be a mix like keep the name **elm-pointer-events** which is most descriptive, but have modules under `Html.Events.Extra`?

**Comment by michaeljones** [comment]
I'm afraid I'm going to much help with the naming, but I would appreciate the rename as I'm running into the `elm-lang/mouse` clash too.

To the extent that they are all Html related, ultimately it feels like they could be under `Html`, but maybe that same logic applies to the main `elm-lang/mouse` module unless the long term plan for that is cross-platform support.

**Comment by mpizenberg** [comment]
In the end, I kept elm-pointer-events which is most specific. However imports are all namespaced under `Html.Events.Extra...` to avoid conflicts. More info in [changelog](https://github.com/mpizenberg/elm-pointer-events/blob/master/CHANGELOG.md).
