### ISSUE TITLE
onUp not always triggered

### ISSUE THREAD

**Issue by leonardorame** [mpizenberg/elm-pointer-events#27]
Hi, I noticed `Mouse.onUp` is not triggered when I follow this process:

1. Press the mouse button (the `onDown` is triggered)
2. Start moving (the `onMove` is triggered)
3. Without stopping moving release the mouse button (`onUp` isn't triggered).

But in 3, if I stop moving and release the mouse button the `onUp` is triggered.

Do you know how can I workaround this issue?

**Comment by mpizenberg** [comment]
Hi @leonardorame I don’t think I’ve experienced this as described above already. The closest thing I can think of is the fact that mouse up events are only triggered if the mouse is still over the area where the event is attached. Meaning if your movement brings your mouse out of the area, the mouseup event will not get captured.

If you issue is the capture problem I just described then you have two options:

1. Listen to events on the whole document, you can use [`Browser.Events` module](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Events#onMouseUp) for that
2. Add a port to be call the JS function that enables **capture** of the mouse event, which will then enable triggering of mouseup event anywhere, like in case (1). You can use the [`examples/Pointer` directory](https://github.com/mpizenberg/elm-pointer-events/blob/master/examples/Pointer/index.html#L22) as an example of how to do that.

Let me know if this solves your issue

**Comment by leonardorame** [comment]
Thanks @mpizenberg for your quick answer.

Ok I'll try the first option, since I'm pretty sure the mouse doesn't leave the element where the `onMove` was started.

**Comment by mpizenberg** [comment]
If you eventually find the original issue, don’t hesitate to circle back and let me know in this issue. The lib is on low maintenance but if there is a bug, better fix it before next time I have to make a release.

**Comment by leonardorame** [comment]
Ok, I added a GlobalMouseUp event and by looking at the Elm Debugger I can see both, the UP and GlobalMouseUp messages are called.
So, apparently is not a problem of the library, but my code...

**Comment by leonardorame** [comment]
The solution was using `onWithOptions` in both, `mousedown` and `mouseup`:

```
canvas                                                                                                                                                                                                               
            [ Html.Attributes.width (bcr.width - 4 |> round)                                                                                                                                                                                 
            , Html.Attributes.height (bcr.height - 4 |> round)                                                                                                                                                                               
            , Mouse.onWithOptions "mousedown" { stopPropagation = True, preventDefault = True } (Down id layoutcell)                                                                                                                         
            , Mouse.onMove (Move id layoutcell)                                                                                                                                                                                              
            , Mouse.onWithOptions "mouseup" { stopPropagation = True, preventDefault = True } (Up id layoutcell)                                                                                                                             
            , Mouse.onLeave (Leave id layoutcell)                                                                                                                                                                                            
            ] [])   
```
