### ISSUE TITLE
Pointer.onUp does not work in OSX Safari

### ISSUE THREAD

**Issue by robert-wallis** [mpizenberg/elm-pointer-events#8]
This code works in Chrome, and Mobile Safari.  But not in OSX Safari
No events are fired, I even put a breakpoint on the event in Safari dev tools. 😢 
https://ellie-app.com/dFHDsBsFza1/3
```elm
module Main exposing (main)

import Html exposing (Html, div, text)
import Html.Attributes exposing (style)
import Pointer

type Msg a = ClickUp a

update msg model =
    case msg of
        ClickUp pos ->
            toString pos


view model =
    div
        [ style [ ( "width", "100%" ), ( "height", "100%" ) ]
        , Pointer.onUp (.pointer >> .clientPos >> ClickUp)
        ]
        [ text model ]


main =
    Html.beginnerProgram
        { model = "click here in OSX Safari"
        , view = view
        , update = update
        }
```

**Comment by robert-wallis** [comment]
Oh I see, it's known to not be supported :(
https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent

**Comment by mpizenberg** [comment]
Yep Safari is not up to the game :(
I've this on the readme:
> Beware though, that the pointer API is not well supported by all browsers. Firefox < 59 and Safari do not natively support pointer events. So I strongly recommend to use this package in pair with the [elm-pep](https://github.com/mpizenberg/elm-pep) polyfill for compatibility with major browsers.

If you think it's not visible enough, let me know and I could make it so it's more visible at the top of the readme.
